import React, { useState, useEffect } from "react";
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  PDFViewer
} from "@react-pdf/renderer";


// Create styles
const styles = StyleSheet.create({
  page: {
    backgroundColor: "white",
    color: "black",
    padding: 20,
  },
  section: {
    flexDirection: 'row',
    borderBottom: 1,
    borderBottomColor: '#808080',
    display: 'flex',
    justifyContent: 'space-between',
    paddingTop: 10,
    paddingBottom: 10,
  },
  viewer: {
    width: window.innerWidth, //the pdf viewer will take up all of the width and height
    height: window.innerHeight,
  },
  heading: {
    fontSize: 16,
    textAlign: 'center',
  },
  userDetails: {
    fontSize: 14,
    fontWeight: 1000,
    color: '#000080',
    marginTop: 20,
    marginBottom: 8,
  },
  address: {
    fontSize: 10,
  }
});


// Create Document Component 
export default function CertificateForFile() {
  const [loginUseremail, setLoginUseremail] = useState();
  const [chatUseremail, setChatUseremail] = useState();
  const [loginUsername, setLoginUsername] = useState();
  const [chatUsername, setChatUsername] = useState();
  const [dateTime, setDateTime] = useState();
  const [fileUrl, setFileUrl] = useState();


  useEffect(async () => {
    const loginUser1 = JSON.parse(localStorage.getItem('chat-app-current-user'));
    setLoginUseremail(loginUser1.email);
    setLoginUsername(loginUser1.username);
    const chatUser = JSON.parse(localStorage.getItem('current-chat-with'));
    setChatUsername(chatUser.username);
    setChatUseremail(chatUser.email);
    setDateTime(localStorage.getItem('dateTimeFile'))
    setFileUrl(localStorage.getItem('fileUrl'))

  }, [])

  return (
    <PDFViewer style={styles.viewer}>
      {/* Start of the document*/}
      <Document>
        {/*render a single page*/}
        <Page size="A4" style={styles.page}>
          <Text style={styles.heading}> Certificate Generated By VAULTIO</Text>

          <Text style={styles.userDetails}>File Details</Text>

          {/* <View style={styles.section}>
            <Text style={styles.address}>File url</Text>
            <Text style={styles.address}><a href={fileUrl} target="_blank"></a> {fileUrl}</Text>
          </View> */}

          <View style={styles.section}>
            <Text style={styles.address}>Sender Username</Text>
            <Text style={styles.address}>{loginUsername}</Text>
          </View>

          <View style={styles.section}>
            <Text style={styles.address}>Sender Email</Text>
            <Text style={styles.address}>{chatUsername}</Text>
          </View>
          <View style={styles.section}>
            <Text style={styles.address}>Reciver Username</Text>
            <Text style={styles.address}>{loginUseremail}</Text>
          </View>
          <View style={styles.section}>
            <Text style={styles.address}>Reciver Email</Text>
            <Text style={styles.address}>{chatUseremail}</Text>
          </View>
          <View style={styles.section}>
            <Text style={styles.address}>Date & Time</Text>
            <Text style={styles.address}>{dateTime}</Text>
          </View>

          {/* <Text style={styles.userDetails}>Receiver</Text>

          <View style={styles.section}>
            <Text style={styles.address}>Metamask Address</Text>
            <Text style={styles.address}>{chatUser}</Text>
          </View>

          <View style={styles.section}>
            <Text style={styles.address}>Email</Text>
            <Text style={styles.address}>{chatUseremail}</Text>
          </View> */}

          {/* <Text style={styles.userDetails}>Audit Trail</Text>

          <View style={styles.section}>
            <Text style={styles.address}>Date And Time</Text>
            <Text style={styles.address}>Recipient</Text>
            <Text style={styles.address}>Action</Text>
            <Text style={styles.address}>IP Address</Text>
            <Text style={styles.address}>Other</Text>
          </View> */}
          {/* <View style={styles.section}>
            <Text style={styles.address}>{requestedTime}</Text>
            <Text style={styles.address}>{loginUsername}</Text>
            <Text style={styles.address}>Created</Text>
            <Text style={styles.address}>{requestedIpAddress1}</Text>
            <Text style={styles.address}>-</Text>
          </View>
          <View style={styles.section}>
            <Text style={styles.address}>{signedTime}</Text>
            <Text style={styles.address}>{chatUsername}</Text>
            <Text style={styles.address}>Signed</Text>
            <Text style={styles.address}>{signedIpAddress1}</Text>
            <Text style={styles.address}>-</Text>
          </View> */}


        </Page>
      </Document>
    </PDFViewer>
  );
}